import * as i from '@xentom/integration-framework'
import * as v from 'valibot'

import * as common from './common'

export const eventType = i.pins.data({
  description: 'The type of tax ID event to trigger on.',
  control: i.controls.select({
    options: [
      { label: 'Created', value: 'created' },
      { label: 'Updated', value: 'updated' },
      { label: 'Deleted', value: 'deleted' },
    ],
    defaultValue: 'created',
  } as const),
})

export const id = common.id.with({
  displayName: 'Tax ID',
  description: 'The unique identifier for the tax ID.',
  control: i.controls.text({
    placeholder: 'txi_...',
  }),
  schema: v.pipe(v.string(), v.startsWith('txi_')),
})

export const type = i.pins.data({
  displayName: 'Tax ID Type',
  description: 'Type of the tax ID.',
  schema: v.string(),
  control: i.controls.select({
    options: [
      { value: 'eu_vat', label: 'EU VAT' },
      { value: 'gb_vat', label: 'GB VAT' },
      { value: 'us_ein', label: 'US EIN' },
      { value: 'au_abn', label: 'AU ABN' },
      { value: 'au_arn', label: 'AU ARN' },
      { value: 'br_cnpj', label: 'BR CNPJ' },
      { value: 'br_cpf', label: 'BR CPF' },
      { value: 'ca_bn', label: 'CA BN' },
      { value: 'ca_gst_hst', label: 'CA GST/HST' },
      { value: 'ca_pst_bc', label: 'CA PST BC' },
      { value: 'ca_pst_mb', label: 'CA PST MB' },
      { value: 'ca_pst_sk', label: 'CA PST SK' },
      { value: 'ca_qst', label: 'CA QST' },
      { value: 'ch_vat', label: 'CH VAT' },
      { value: 'cl_tin', label: 'CL TIN' },
      { value: 'es_cif', label: 'ES CIF' },
      { value: 'hk_br', label: 'HK BR' },
      { value: 'id_npwp', label: 'ID NPWP' },
      { value: 'il_vat', label: 'IL VAT' },
      { value: 'in_gst', label: 'IN GST' },
      { value: 'jp_cn', label: 'JP CN' },
      { value: 'jp_rn', label: 'JP RN' },
      { value: 'jp_trn', label: 'JP TRN' },
      { value: 'kr_brn', label: 'KR BRN' },
      { value: 'mx_rfc', label: 'MX RFC' },
      { value: 'my_frp', label: 'MY FRP' },
      { value: 'my_itn', label: 'MY ITN' },
      { value: 'my_sst', label: 'MY SST' },
      { value: 'no_vat', label: 'NO VAT' },
      { value: 'nz_gst', label: 'NZ GST' },
      { value: 'ru_inn', label: 'RU INN' },
      { value: 'ru_kpp', label: 'RU KPP' },
      { value: 'sa_vat', label: 'SA VAT' },
      { value: 'sg_gst', label: 'SG GST' },
      { value: 'sg_uen', label: 'SG UEN' },
      { value: 'th_vat', label: 'TH VAT' },
      { value: 'tw_vat', label: 'TW VAT' },
      { value: 'za_vat', label: 'ZA VAT' },
      { value: 'ad_nrt', label: 'AD NRT' },
      { value: 'ae_trn', label: 'AE TRN' },
      { value: 'ar_cuit', label: 'AR CUIT' },
      { value: 'bg_uic', label: 'BG UIC' },
      { value: 'bh_vat', label: 'BH VAT' },
      { value: 'bo_tin', label: 'BO TIN' },
      { value: 'by_tin', label: 'BY TIN' },
      { value: 'ch_uid', label: 'CH UID' },
      { value: 'cn_tin', label: 'CN TIN' },
      { value: 'co_nit', label: 'CO NIT' },
      { value: 'cr_tin', label: 'CR TIN' },
      { value: 'de_stn', label: 'DE STN' },
      { value: 'do_rcn', label: 'DO RCN' },
      { value: 'ec_ruc', label: 'EC RUC' },
      { value: 'eg_tin', label: 'EG TIN' },
      { value: 'eu_oss_vat', label: 'EU OSS VAT' },
      { value: 'ge_vat', label: 'GE VAT' },
      { value: 'gn_nif', label: 'GN NIF' },
      { value: 'hr_oib', label: 'HR OIB' },
      { value: 'hu_tin', label: 'HU TIN' },
      { value: 'is_vat', label: 'IS VAT' },
      { value: 'ke_pin', label: 'KE PIN' },
      { value: 'kz_bin', label: 'KZ BIN' },
      { value: 'li_uid', label: 'LI UID' },
      { value: 'li_vat', label: 'LI VAT' },
      { value: 'ma_vat', label: 'MA VAT' },
      { value: 'md_vat', label: 'MD VAT' },
      { value: 'me_pib', label: 'ME PIB' },
      { value: 'mk_vat', label: 'MK VAT' },
      { value: 'mr_nif', label: 'MR NIF' },
      { value: 'ng_tin', label: 'NG TIN' },
      { value: 'no_voec', label: 'NO VOEC' },
      { value: 'om_vat', label: 'OM VAT' },
      { value: 'pe_ruc', label: 'PE RUC' },
      { value: 'ph_tin', label: 'PH TIN' },
      { value: 'ro_tin', label: 'RO TIN' },
      { value: 'rs_pib', label: 'RS PIB' },
      { value: 'si_tin', label: 'SI TIN' },
      { value: 'sn_ninea', label: 'SN NINEA' },
      { value: 'sr_fin', label: 'SR FIN' },
      { value: 'sv_nit', label: 'SV NIT' },
      { value: 'tn_vat', label: 'TN VAT' },
      { value: 'tr_tin', label: 'TR TIN' },
      { value: 'tz_vat', label: 'TZ VAT' },
      { value: 'ua_vat', label: 'UA VAT' },
      { value: 'uy_ruc', label: 'UY RUC' },
      { value: 'uz_tin', label: 'UZ TIN' },
      { value: 've_rif', label: 'VE RIF' },
      { value: 'vn_tin', label: 'VN TIN' },
      { value: 'zm_tin', label: 'ZM TIN' },
      { value: 'zw_tin', label: 'ZW TIN' },
    ],
  }),
})

export const value = i.pins.data({
  displayName: 'Tax ID Value',
  description: 'Value of the tax ID.',
  schema: v.pipe(v.string(), v.nonEmpty()),
  control: i.controls.text({
    placeholder: 'DE123456789',
  }),
})
